//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 07:57:09 PM CST 
//


package cn.issboy.mengine.parser.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTypeRestriction.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataTypeRestriction">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="synthea"/>
 *     &lt;enumeration value="mhealth"/>
 *     &lt;enumeration value="hybrid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataTypeRestriction")
@XmlEnum
public enum DataTypeRestriction {

    @XmlEnumValue("synthea")
    SYNTHEA("synthea"),
    @XmlEnumValue("mhealth")
    MHEALTH("mhealth"),
    @XmlEnumValue("hybrid")
    HYBRID("hybrid");
    private final String value;

    DataTypeRestriction(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataTypeRestriction fromValue(String v) {
        for (DataTypeRestriction c: DataTypeRestriction.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
