//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 07:57:09 PM CST 
//


package cn.issboy.mengine.parser.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="join_type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Dynamic-Join-Dynamic"/>
 *               &lt;enumeration value="Dynamic-Join-Static"/>
 *               &lt;enumeration value="Static-Join-Static"/>
 *               &lt;enumeration value="Other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="join_targets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="target" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="left" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="join_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinType", propOrder = {
    "joinType",
    "joinTargets"
})
public class JoinType {

    @XmlElement(name = "join_type")
    protected String joinType;
    @XmlElement(name = "join_targets")
    protected JoinType.JoinTargets joinTargets;

    /**
     * Gets the value of the joinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinType() {
        return joinType;
    }

    /**
     * Sets the value of the joinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinType(String value) {
        this.joinType = value;
    }

    /**
     * Gets the value of the joinTargets property.
     * 
     * @return
     *     possible object is
     *     {@link JoinType.JoinTargets }
     *     
     */
    public JoinType.JoinTargets getJoinTargets() {
        return joinTargets;
    }

    /**
     * Sets the value of the joinTargets property.
     * 
     * @param value
     *     allowed object is
     *     {@link JoinType.JoinTargets }
     *     
     */
    public void setJoinTargets(JoinType.JoinTargets value) {
        this.joinTargets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="target" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="left" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="join_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "target"
    })
    public static class JoinTargets {

        protected List<JoinType.JoinTargets.Target> target;

        /**
         * Gets the value of the target property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the target property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTarget().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JoinType.JoinTargets.Target }
         * 
         * 
         */
        public List<JoinType.JoinTargets.Target> getTarget() {
            if (target == null) {
                target = new ArrayList<JoinType.JoinTargets.Target>();
            }
            return this.target;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="left" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="join_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Target {

            @XmlSchemaType(name = "unsignedInt")
            protected long id;
            @XmlElement(required = true)
            protected String left;
            @XmlElement(required = true)
            protected String right;
            @XmlElement(name = "join_type", required = true)
            protected String joinType;
            @XmlElement(required = true)
            protected String source;
            @XmlElement(required = true)
            protected String condition;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the left property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLeft() {
                return left;
            }

            /**
             * Sets the value of the left property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLeft(String value) {
                this.left = value;
            }

            /**
             * Gets the value of the right property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRight() {
                return right;
            }

            /**
             * Sets the value of the right property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRight(String value) {
                this.right = value;
            }

            /**
             * Gets the value of the joinType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJoinType() {
                return joinType;
            }

            /**
             * Sets the value of the joinType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJoinType(String value) {
                this.joinType = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the condition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCondition(String value) {
                this.condition = value;
            }

        }

    }

}
