//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 07:57:09 PM CST 
//


package cn.issboy.mengine.parser.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KafkaConnectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KafkaConnectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bootstrap_server" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schema_registry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="application_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="key_serializer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="key_deserializer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value_serializer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value_deserializer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KafkaConnectionType", propOrder = {
    "bootstrapServer",
    "schemaRegistry",
    "applicationId",
    "keySerializer",
    "keyDeserializer",
    "valueSerializer",
    "valueDeserializer"
})
public class KafkaConnectionType {

    @XmlElement(name = "bootstrap_server", required = true)
    protected String bootstrapServer;
    @XmlElement(name = "schema_registry", required = true)
    protected String schemaRegistry;
    @XmlElement(name = "application_id", required = true)
    protected String applicationId;
    @XmlElement(name = "key_serializer", required = true)
    protected String keySerializer;
    @XmlElement(name = "key_deserializer", required = true)
    protected String keyDeserializer;
    @XmlElement(name = "value_serializer", required = true)
    protected String valueSerializer;
    @XmlElement(name = "value_deserializer", required = true)
    protected String valueDeserializer;

    /**
     * Gets the value of the bootstrapServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBootstrapServer() {
        return bootstrapServer;
    }

    /**
     * Sets the value of the bootstrapServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBootstrapServer(String value) {
        this.bootstrapServer = value;
    }

    /**
     * Gets the value of the schemaRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaRegistry() {
        return schemaRegistry;
    }

    /**
     * Sets the value of the schemaRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaRegistry(String value) {
        this.schemaRegistry = value;
    }

    /**
     * Gets the value of the applicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets the value of the applicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationId(String value) {
        this.applicationId = value;
    }

    /**
     * Gets the value of the keySerializer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeySerializer() {
        return keySerializer;
    }

    /**
     * Sets the value of the keySerializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeySerializer(String value) {
        this.keySerializer = value;
    }

    /**
     * Gets the value of the keyDeserializer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyDeserializer() {
        return keyDeserializer;
    }

    /**
     * Sets the value of the keyDeserializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyDeserializer(String value) {
        this.keyDeserializer = value;
    }

    /**
     * Gets the value of the valueSerializer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSerializer() {
        return valueSerializer;
    }

    /**
     * Sets the value of the valueSerializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSerializer(String value) {
        this.valueSerializer = value;
    }

    /**
     * Gets the value of the valueDeserializer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueDeserializer() {
        return valueDeserializer;
    }

    /**
     * Sets the value of the valueDeserializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueDeserializer(String value) {
        this.valueDeserializer = value;
    }

}
