//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 07:57:09 PM CST 
//


package cn.issboy.mengine.parser.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasource">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="kafka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="connection" type="{}KafkaConnectionType"/>
 *                             &lt;element name="datasink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="elasticsearch">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="connection" type="{}ElasticSearchConnection"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="opentsdb">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="connection" type="{}OpentsdbConnection"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="grafana">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="connection" type="{}GrafanaConnection"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dashboard">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="panels">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="panel" type="{}PanelType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pattern">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pattern_lib">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="instance" type="{}PatternType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="monitor-queries">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="query" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="target" type="{}DataDescription"/>
 *                             &lt;element name="operation" type="{}OperationDescription"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datasource",
    "dashboard",
    "pattern",
    "monitorQueries"
})
@XmlRootElement(name = "monitor")
public class Monitor {

    @XmlElement(required = true)
    protected Monitor.Datasource datasource;
    @XmlElement(required = true)
    protected Monitor.Dashboard dashboard;
    @XmlElement(required = true)
    protected Monitor.Pattern pattern;
    @XmlElement(name = "monitor-queries", required = true)
    protected Monitor.MonitorQueries monitorQueries;

    /**
     * Gets the value of the datasource property.
     * 
     * @return
     *     possible object is
     *     {@link Monitor.Datasource }
     *     
     */
    public Monitor.Datasource getDatasource() {
        return datasource;
    }

    /**
     * Sets the value of the datasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitor.Datasource }
     *     
     */
    public void setDatasource(Monitor.Datasource value) {
        this.datasource = value;
    }

    /**
     * Gets the value of the dashboard property.
     * 
     * @return
     *     possible object is
     *     {@link Monitor.Dashboard }
     *     
     */
    public Monitor.Dashboard getDashboard() {
        return dashboard;
    }

    /**
     * Sets the value of the dashboard property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitor.Dashboard }
     *     
     */
    public void setDashboard(Monitor.Dashboard value) {
        this.dashboard = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link Monitor.Pattern }
     *     
     */
    public Monitor.Pattern getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitor.Pattern }
     *     
     */
    public void setPattern(Monitor.Pattern value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the monitorQueries property.
     * 
     * @return
     *     possible object is
     *     {@link Monitor.MonitorQueries }
     *     
     */
    public Monitor.MonitorQueries getMonitorQueries() {
        return monitorQueries;
    }

    /**
     * Sets the value of the monitorQueries property.
     * 
     * @param value
     *     allowed object is
     *     {@link Monitor.MonitorQueries }
     *     
     */
    public void setMonitorQueries(Monitor.MonitorQueries value) {
        this.monitorQueries = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="panels">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="panel" type="{}PanelType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "panels"
    })
    public static class Dashboard {

        @XmlElement(required = true)
        protected Monitor.Dashboard.Panels panels;

        /**
         * Gets the value of the panels property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Dashboard.Panels }
         *     
         */
        public Monitor.Dashboard.Panels getPanels() {
            return panels;
        }

        /**
         * Sets the value of the panels property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Dashboard.Panels }
         *     
         */
        public void setPanels(Monitor.Dashboard.Panels value) {
            this.panels = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="panel" type="{}PanelType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "panel"
        })
        public static class Panels {

            protected List<PanelType> panel;

            /**
             * Gets the value of the panel property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the panel property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPanel().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PanelType }
             * 
             * 
             */
            public List<PanelType> getPanel() {
                if (panel == null) {
                    panel = new ArrayList<PanelType>();
                }
                return this.panel;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="kafka">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="connection" type="{}KafkaConnectionType"/>
     *                   &lt;element name="datasink" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="elasticsearch">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="connection" type="{}ElasticSearchConnection"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="opentsdb">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="connection" type="{}OpentsdbConnection"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="grafana">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="connection" type="{}GrafanaConnection"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Datasource {

        @XmlElement(required = true)
        protected Monitor.Datasource.Kafka kafka;
        @XmlElement(required = true)
        protected Monitor.Datasource.Elasticsearch elasticsearch;
        @XmlElement(required = true)
        protected Monitor.Datasource.Opentsdb opentsdb;
        @XmlElement(required = true)
        protected Monitor.Datasource.Grafana grafana;

        /**
         * Gets the value of the kafka property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Datasource.Kafka }
         *     
         */
        public Monitor.Datasource.Kafka getKafka() {
            return kafka;
        }

        /**
         * Sets the value of the kafka property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Datasource.Kafka }
         *     
         */
        public void setKafka(Monitor.Datasource.Kafka value) {
            this.kafka = value;
        }

        /**
         * Gets the value of the elasticsearch property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Datasource.Elasticsearch }
         *     
         */
        public Monitor.Datasource.Elasticsearch getElasticsearch() {
            return elasticsearch;
        }

        /**
         * Sets the value of the elasticsearch property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Datasource.Elasticsearch }
         *     
         */
        public void setElasticsearch(Monitor.Datasource.Elasticsearch value) {
            this.elasticsearch = value;
        }

        /**
         * Gets the value of the opentsdb property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Datasource.Opentsdb }
         *     
         */
        public Monitor.Datasource.Opentsdb getOpentsdb() {
            return opentsdb;
        }

        /**
         * Sets the value of the opentsdb property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Datasource.Opentsdb }
         *     
         */
        public void setOpentsdb(Monitor.Datasource.Opentsdb value) {
            this.opentsdb = value;
        }

        /**
         * Gets the value of the grafana property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Datasource.Grafana }
         *     
         */
        public Monitor.Datasource.Grafana getGrafana() {
            return grafana;
        }

        /**
         * Sets the value of the grafana property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Datasource.Grafana }
         *     
         */
        public void setGrafana(Monitor.Datasource.Grafana value) {
            this.grafana = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="connection" type="{}ElasticSearchConnection"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "connection"
        })
        public static class Elasticsearch {

            @XmlElement(required = true)
            protected ElasticSearchConnection connection;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link ElasticSearchConnection }
             *     
             */
            public ElasticSearchConnection getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link ElasticSearchConnection }
             *     
             */
            public void setConnection(ElasticSearchConnection value) {
                this.connection = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="connection" type="{}GrafanaConnection"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "connection"
        })
        public static class Grafana {

            @XmlElement(required = true)
            protected GrafanaConnection connection;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link GrafanaConnection }
             *     
             */
            public GrafanaConnection getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link GrafanaConnection }
             *     
             */
            public void setConnection(GrafanaConnection value) {
                this.connection = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="connection" type="{}KafkaConnectionType"/>
         *         &lt;element name="datasink" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "connection",
            "datasink"
        })
        public static class Kafka {

            @XmlElement(required = true)
            protected KafkaConnectionType connection;
            @XmlElement(required = true)
            protected String datasink;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link KafkaConnectionType }
             *     
             */
            public KafkaConnectionType getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link KafkaConnectionType }
             *     
             */
            public void setConnection(KafkaConnectionType value) {
                this.connection = value;
            }

            /**
             * Gets the value of the datasink property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatasink() {
                return datasink;
            }

            /**
             * Sets the value of the datasink property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatasink(String value) {
                this.datasink = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="connection" type="{}OpentsdbConnection"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "connection"
        })
        public static class Opentsdb {

            @XmlElement(required = true)
            protected OpentsdbConnection connection;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link OpentsdbConnection }
             *     
             */
            public OpentsdbConnection getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link OpentsdbConnection }
             *     
             */
            public void setConnection(OpentsdbConnection value) {
                this.connection = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="query" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="target" type="{}DataDescription"/>
     *                   &lt;element name="operation" type="{}OperationDescription"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "query"
    })
    public static class MonitorQueries {

        protected List<Monitor.MonitorQueries.Query> query;

        /**
         * Gets the value of the query property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the query property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuery().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Monitor.MonitorQueries.Query }
         * 
         * 
         */
        public List<Monitor.MonitorQueries.Query> getQuery() {
            if (query == null) {
                query = new ArrayList<Monitor.MonitorQueries.Query>();
            }
            return this.query;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="target" type="{}DataDescription"/>
         *         &lt;element name="operation" type="{}OperationDescription"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "target",
            "operation"
        })
        public static class Query {

            @XmlElement(required = true)
            protected DataDescription target;
            @XmlElement(required = true)
            protected OperationDescription operation;
            @XmlAttribute(name = "id", required = true)
            @XmlSchemaType(name = "unsignedInt")
            protected long id;

            /**
             * Gets the value of the target property.
             * 
             * @return
             *     possible object is
             *     {@link DataDescription }
             *     
             */
            public DataDescription getTarget() {
                return target;
            }

            /**
             * Sets the value of the target property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataDescription }
             *     
             */
            public void setTarget(DataDescription value) {
                this.target = value;
            }

            /**
             * Gets the value of the operation property.
             * 
             * @return
             *     possible object is
             *     {@link OperationDescription }
             *     
             */
            public OperationDescription getOperation() {
                return operation;
            }

            /**
             * Sets the value of the operation property.
             * 
             * @param value
             *     allowed object is
             *     {@link OperationDescription }
             *     
             */
            public void setOperation(OperationDescription value) {
                this.operation = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pattern_lib">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="instance" type="{}PatternType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "patternLib"
    })
    public static class Pattern {

        @XmlElement(name = "pattern_lib", required = true)
        protected Monitor.Pattern.PatternLib patternLib;

        /**
         * Gets the value of the patternLib property.
         * 
         * @return
         *     possible object is
         *     {@link Monitor.Pattern.PatternLib }
         *     
         */
        public Monitor.Pattern.PatternLib getPatternLib() {
            return patternLib;
        }

        /**
         * Sets the value of the patternLib property.
         * 
         * @param value
         *     allowed object is
         *     {@link Monitor.Pattern.PatternLib }
         *     
         */
        public void setPatternLib(Monitor.Pattern.PatternLib value) {
            this.patternLib = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="instance" type="{}PatternType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "instance"
        })
        public static class PatternLib {

            protected List<PatternType> instance;

            /**
             * Gets the value of the instance property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the instance property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInstance().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PatternType }
             * 
             * 
             */
            public List<PatternType> getInstance() {
                if (instance == null) {
                    instance = new ArrayList<PatternType>();
                }
                return this.instance;
            }

        }

    }

}
