//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 07:57:09 PM CST 
//


package cn.issboy.mengine.parser.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="join" type="{}JoinType"/>
 *         &lt;element name="group" type="{}GroupType"/>
 *         &lt;element name="select" type="{}SelectType"/>
 *         &lt;element name="window" type="{}WindowType"/>
 *         &lt;element name="growth" type="{}GrowthType"/>
 *         &lt;element name="aggregation" type="{}AggregationType"/>
 *         &lt;element name="filter" type="{}FilterType"/>
 *         &lt;element name="characteristic" type="{}CharacteristicType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationDescription", propOrder = {
    "join",
    "group",
    "select",
    "window",
    "growth",
    "aggregation",
    "filter",
    "characteristic"
})
public class OperationDescription {

    @XmlElement(required = true)
    protected JoinType join;
    @XmlElement(required = true)
    protected GroupType group;
    @XmlElement(required = true)
    protected SelectType select;
    @XmlElement(required = true)
    protected WindowType window;
    @XmlElement(required = true)
    protected GrowthType growth;
    @XmlElement(required = true)
    protected AggregationType aggregation;
    @XmlElement(required = true)
    protected FilterType filter;
    @XmlElement(required = true)
    protected CharacteristicType characteristic;

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link JoinType }
     *     
     */
    public JoinType getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link JoinType }
     *     
     */
    public void setJoin(JoinType value) {
        this.join = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link GroupType }
     *     
     */
    public GroupType getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupType }
     *     
     */
    public void setGroup(GroupType value) {
        this.group = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link SelectType }
     *     
     */
    public SelectType getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectType }
     *     
     */
    public void setSelect(SelectType value) {
        this.select = value;
    }

    /**
     * Gets the value of the window property.
     * 
     * @return
     *     possible object is
     *     {@link WindowType }
     *     
     */
    public WindowType getWindow() {
        return window;
    }

    /**
     * Sets the value of the window property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowType }
     *     
     */
    public void setWindow(WindowType value) {
        this.window = value;
    }

    /**
     * Gets the value of the growth property.
     * 
     * @return
     *     possible object is
     *     {@link GrowthType }
     *     
     */
    public GrowthType getGrowth() {
        return growth;
    }

    /**
     * Sets the value of the growth property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrowthType }
     *     
     */
    public void setGrowth(GrowthType value) {
        this.growth = value;
    }

    /**
     * Gets the value of the aggregation property.
     * 
     * @return
     *     possible object is
     *     {@link AggregationType }
     *     
     */
    public AggregationType getAggregation() {
        return aggregation;
    }

    /**
     * Sets the value of the aggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregationType }
     *     
     */
    public void setAggregation(AggregationType value) {
        this.aggregation = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link FilterType }
     *     
     */
    public FilterType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterType }
     *     
     */
    public void setFilter(FilterType value) {
        this.filter = value;
    }

    /**
     * Gets the value of the characteristic property.
     * 
     * @return
     *     possible object is
     *     {@link CharacteristicType }
     *     
     */
    public CharacteristicType getCharacteristic() {
        return characteristic;
    }

    /**
     * Sets the value of the characteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharacteristicType }
     *     
     */
    public void setCharacteristic(CharacteristicType value) {
        this.characteristic = value;
    }

}
